name: nemo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - pip:
      - jupyterlab
      - matplotlib==3.10.0
      - nibabel==5.3.2
      - numpy==2.2.1
      - pandas==2.2.3
      - pillow==11.1.0
      - plotly==5.24.1
      - scikit-image==0.25.0
      - scikit-learn==1.6.1
      - scipy==1.15.0
      - seaborn==0.13.2
      - statsmodels==0.14.4
