#!/usr/bin/env python3
import json
import os
import sys
import pandas as pd
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent.parent))
import utils
from rsfmri.run_xcpd import is_already_processed as is_xcpd_done


def run_participant_qc(config, subject, session, job_ids=None):
    """
    Run QC and MRIQC on XCP-D outputs for a given subject and session.

    Parameters
    ----------
    config: 
        Configuration object.
    subject: str
        Subject identifier.
    session: str
        Session identifier.
    job_ids: list, optional
        List of SLURM job IDs to set as dependencies (default is None).
    """

    common = config["common"]
    DERIVATIVES_DIR = common["derivatives"]
    mriqc = config["mriqc"]

    if not is_xcpd_done(config, subject, session):
        print(f"[QC-XCPD] XCP-D did not terminate for {subject} {session}. Please run XCP-D command before QC.")
        return None

    # Create output (derivatives) directories
    os.makedirs(f"{DERIVATIVES_DIR}/qc/xcpd", exist_ok=True)
    os.makedirs(f"{DERIVATIVES_DIR}/qc/xcpd/outputs/{subject}/{session}", exist_ok=True)
    os.makedirs(f"{DERIVATIVES_DIR}/qc/xcpd/stdout", exist_ok=True)

    # Run in interactive mode to avoid using resources on the connection front
    # It is also mandatory to ensure correct orchestration and wait for previous jobs to be terminated
    print(f"[QC-XCPD] Submitting QC metric extraction in (background) interactive mode")
    cmd = (f'\nsrun --job-name=fsqc --ntasks=1 '
           f'--partition={mriqc["partition"]} '
           f'--mem={mriqc["requested_mem"]} '
           f'--time={mriqc["requested_time"]} '
           f'--out={DERIVATIVES_DIR}/qc/xcpd/stdout/qc_xcpd_{subject}_{session}_%j.out '
           f'--err={DERIVATIVES_DIR}/qc/xcpd/stdout/qc_xcpd_{subject}_{session}_%j.err ')
    if job_ids:
        cmd += f'--dependency=afterok:{":".join(job_ids)} '
    # Call to python scripts for the rest of QC
    cmd += f"python3 rsfmri/qc_xcpd.py '{json.dumps(config)}' participant {subject} {session} &"
    os.system(cmd)


def run_group_qc(config, job_ids=None):

    common = config["common"]
    DERIVATIVES_DIR = common["derivatives"]
    mriqc = config["mriqc"]

    # Run in interactive mode to avoid using resources on the connection front
    # It is also mandatory to ensure correct orchestration and wait for previous jobs to be terminated
    print(f"[QSIRECON-GROUP-QC] Performing QC metric concatenation in (background) interactive mode")
    cmd = (f'\nsrun --job-name=fsqc --ntasks=1 '
           f'--partition={mriqc["partition"]} '
           f'--mem={mriqc["requested_mem"]} '
           f'--time={mriqc["requested_time"]} '
           f'--out={DERIVATIVES_DIR}/qc/xcpd/stdout/qc_group_xcpd_%j.out '
           f'--err={DERIVATIVES_DIR}/qc/xcpd/stdout/qc_group_xcpd_%j.err ')
    if job_ids:
        cmd += f'--dependency=afterok:{":".join(job_ids)} '
    cmd += f"python3 rsfmri/qc_xcpd.py '{json.dumps(config)}' group &"
    os.system(cmd)


# ------------------------------------------
# Metric extraction (call from srun command)
# ------------------------------------------
def metric_extraction(config, subject, session):
    """
    Executes quality control (QC) checks on XCP-D outputs for a given subject and session.
    This function performs the following steps:
    - Sets up output directories for QC results.
    - Locates the XCP-D output directory for the specified subject and session.
    - Extracts processing status and runtime information from logs.
    - Counts the number of directories and files generated by XCP-D.
    - Loads the XCP-D QC metrics file (TSV format) and extracts key metrics such as mean framewise displacement (FD),
      percentage of censored frames, number of retained volumes, and mean DVARS.
    - Applies pass/fail logic based on predefined thresholds for motion and data retention, recording reasons for any failure.
    - Augments the QC metrics DataFrame with additional information (processing status, runtime, counts, fail reasons).
    - Saves the updated QC metrics to a CSV file in the QC output directory.
    - Handles and reports errors gracefully if any step fails.
    config : dict or SimpleNamespace
        Configuration object containing paths and settings, including the derivatives directory.
    subject : str
        Subject identifier (e.g., 'sub-01').
    session : str
        Session identifier (e.g., 'ses-01').
    Raises
    ------
    FileNotFoundError
        If the required XCP-D QC metrics file is not found.
    Exception
        For any other errors encountered during processing, with error details printed to stdout.
    Outputs
    -------
    - Saves an updated QC metrics CSV file in the derivatives QC directory.
    - Prints status messages and error notifications to stdout.
    """

    DERIVATIVES_DIR = config["common"]["derivatives"]
    xcpd_dir = f"{DERIVATIVES_DIR}/xcpd/outputs/{subject}/{session}"

    # Read bids_filter file to get the list of tasks to consider
    tasks = utils.get_tasks(session)

    for task in tasks:
        try:
            # Extract process status from log files
            finished_status, runtime = utils.read_log(config, subject, session, runtype="xcpd")
            dir_count = utils.count_dirs(xcpd_dir)
            file_count = utils.count_files(xcpd_dir)

            # Load TSV file produced by XCP-D
            xcpd_metrics = f'{subject}_{session}_task-{task}_motion.tsv'
            df = pd.read_csv(os.path.join(xcpd_dir, 'func', xcpd_metrics), sep='\t')

            max_framewise_displacement = df['framewise_displacement'].max()
            max_rot_x = df['rot_x'].max()
            max_rot_y = df['rot_y'].max()
            max_rot_z = df['rot_z'].max()
            max_trans_x = df['trans_x'].max()
            max_trans_y = df['trans_y'].max()
            max_trans_z = df['trans_z'].max()
            max_rmsd = df['rmsd'].max()

            row = dict(
                subject=subject,
                session=session,
                Process_Run="xcpd",
                Finished_without_error=finished_status,
                Processing_time_hours=runtime,
                Number_of_folders_generated=dir_count,
                Number_of_files_generated=file_count,
                max_framewise_displacement=max_framewise_displacement,
                max_rot_x=max_rot_x,
                max_rot_y=max_rot_y,
                max_rot_z=max_rot_z,
                max_trans_x=max_trans_x,
                max_trans_y=max_trans_y,
                max_trans_z=max_trans_z,
                max_rmsd=max_rmsd,
            )

            # Save the updated qc_df
            sub_ses_qc = pd.DataFrame([row])
            path_to_qc = f"{DERIVATIVES_DIR}/qc/xcpd/outputs/{subject}/{session}/{subject}_{session}_task-{task}_qc.csv"
            sub_ses_qc.to_csv(path_to_qc, mode='w', header=True, index=False)
            print(f"QC saved in {path_to_qc}\n")

            print(f"XCP-D Quality Check terminated successfully for {subject} {session} task-{task}.")

        except Exception as e:
            print(f"⚠️ ERROR: QC aborted for {subject} {session} task-{task}: \n{e}")


def metric_concatenation(config):

    DERIVATIVES_DIR = config["common"]["derivatives"]

    # Load and Concatenate participant-level metrics
    qc_inhouse = []
    qc_xcpd = []
    # List all subjects and sessions in the QSIprep BIDS output directory
    subjects = utils.get_subjects(f"{DERIVATIVES_DIR}/xcpd/outputs")
    for subject in subjects:
        sessions = utils.get_sessions(f"{DERIVATIVES_DIR}/xcpd/outputs", subject)
        for session in sessions:
            tasks = utils.get_tasks(session)
            for task in tasks:
                # Concatenate in-house metrics
                path_to_qc = Path(f"{DERIVATIVES_DIR}/qc/xcpd/outputs/{subject}/{session}/{subject}_{session}_task-{task}_qc.csv")
                if not path_to_qc.is_file():
                    continue
                qc_inhouse.append(pd.read_csv(path_to_qc))

                # Concatenate QSIPrep metrics
                path_to_func = Path(f"{DERIVATIVES_DIR}/xcpd/outputs/{subject}/{session}/func")
                path_to_qc = next(path_to_func.glob("*_desc-linc_qc.tsv"))
                if not path_to_qc.is_file():
                    continue
                qc_xcpd.append(pd.read_csv(path_to_qc, sep='\t'))

    if qc_inhouse:
        group_qc = pd.concat(qc_inhouse, ignore_index=True)
        path_to_group_qc = f"{DERIVATIVES_DIR}/qc/xcpd/group_minimal_qc.csv"
        group_qc.to_csv(path_to_group_qc, index=False)

    if qc_xcpd:
        group_qc = pd.concat(qc_xcpd, ignore_index=True)
        path_to_group_qc = f"{DERIVATIVES_DIR}/qc/xcpd/group_qsiprep_linc_qc.csv"
        group_qc.to_csv(path_to_group_qc, index=False)

    print(f"[QC-XCPD] Group-level QC saved in {DERIVATIVES_DIR}/qc/xcpd\n")


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3:
        raise RuntimeError(
            "Usage: python qc_xcpd.py <config> participant <subject> <session>"
            "Usage: python qc_xcpd.py <config> group"
        )
    config = json.loads(sys.argv[1])
    level = sys.argv[2]
    if level == 'participant':
        subject = sys.argv[3]
        session = sys.argv[4]
        metric_extraction(config, subject, session)
    if level == 'group':
        metric_concatenation(config)
