# =============================
#   PROJECT-WIDE SETTINGS
# =============================
[common]
freesurfer_license = "/scratch/lhashimoto/freesurfer/license"  # Directory containing license file
python_env = "/scratch/lhashimoto/python/env/nemo"
account = ""
email = ""
email_frequency = "FAIL" # BEGIN,END
## NEMO DATABASE
#input_dir = "/scratch/lhashimoto/nemo_database/imaging_data"
#derivatives = "/scratch/lhashimoto/nemo_derivatives"
#subjects = ["1054001"]  #["1054001","1054002","1054004","1054010"]
#sessions = ["01"]
## BRAINT DATABASE
input_dir = "/scratch/hrasoanandrianina/braint_database"
derivatives = "/scratch/lhashimoto/braint_derivatives"
subjects = ["003"]
sessions = ["01"] #, "02"]
bids_filter_dir = "/scratch/lhashimoto/code/nemo/bids_filters"

# =============================
#   WORKFLOW SETTINGS
# =============================
[workflow]
run_freesurfer = false
run_qsiprep = false
run_qsirecon = false
run_fmriprep = false
run_xcp_d = false
run_raw_qc = false
run_freesurfer_qc = false
run_qsiprep_qc = false
run_qsirecon_qc = false
run_fmriprep_qc = false
run_xcpd_qc = false
run_group_qc = false

# =============================
#   PIPELINE: FreeSurfer
# =============================
[freesurfer]
freesurfer_container = "/scratch/lhashimoto/freesurfer-7.4.1.sif"
use_t2 = true
partition = "skylake"
requested_mem = "16"
requested_time = "9:00:00"
skip_processed = true

# =============================
#   PIPELINE: FreeSurfer QC
# =============================
[fsqc]
fsqc_container = "/scratch/lhashimoto/fsqc-2.1.4.sif"
partition = "skylake"
requested_mem = "16"
requested_time = "0:30:00"
qc_screenshots = true
qc_surfaces = true
qc_skullstrip = true
qc_fornix = true
qc_hypothalamus = false
qc_hippocampus = false
qc_hippocampus_label = ""
qc_outlier = false  # true to get non-ETIV-normalized outliers
qc_skip_existing = false

# =============================
#   PIPELINE: QSIPrep
# =============================
[qsiprep]
qsiprep_container = "/scratch/lhashimoto/qsiprep-1.1.1.sif"
config_eddy = "/scratch/lhashimoto/code/nemo/config/eddy_params.json"
qsiprep_config = "/scratch/lhashimoto/code/nemo/config/qsiprep_config.toml"
output_resolution = 1.8
subject_anatomical_reference = "sessionwise"
partition = "kepler"
gpu_per_node = 2
requested_mem = "70"
requested_time = "24:00:00"
skip_processed = true

# =============================
#   PIPELINE: QSIRecon
# =============================
[qsirecon]
qsirecon_container = "/scratch/lhashimoto/qsirecon-1.1.1.sif"
qsirecon_config = "/scratch/lhashimoto/code/nemo/config/qsirecon_config.toml"
partition = "kepler"
gpu_per_node = 2
requested_mem = "70"
requested_time = "24:00:00"
atlases = ["4S156Parcels"] #, "4S356Parcels"]
skip_processed = true

# =============================
#   PIPELINE: fMRIPrep
# =============================
[fmriprep]
fmriprep_container = "/scratch/lhashimoto/fmriprep-25.2.2.sif"
fmriprep_config = "/scratch/lhashimoto/code/nemo/config/fmriprep_config.toml"
subject_anatomical_reference = "sessionwise"
cifti_outputs = "91k"
reserved_cpus = 8
omp_threads = 4
partition = "skylake"
requested_mem = "64"
requested_time = "12:00:00"
skip_processed = true

# =============================
#   PIPELINE: XCP-D
# =============================
[xcpd]
xcpd_container = "/scratch/lhashimoto/xcpd-0.12.0.sif"
xcpd_config = "/scratch/lhashimoto/code/nemo/config/xcpd_config.toml"
partition = "skylake"
requested_mem = "64"
requested_time = "8:00:00"
reserved_cpus = 8
omp_threads = 4
atlases = ["4S156Parcels"] #, "4S356Parcels"]
skip_processed = true

# =============================
#   PIPELINE: MRIQC
# =============================
[mriqc]
mriqc_container = "/scratch/lhashimoto/mriqc-24.0.2.sif"
mriqc_config = "/scratch/lhashimoto/code/nemo/config/mriqc_config.toml"
partition = "skylake"
requested_mem = "64"
requested_time = "3:00:00"
skip_processed = true
