[environment]

[execution]
# atlases = [ "4S156Parcels",]  # must be given in cmd line
boilerplate_only = false
sloppy = true
debug = []
log_level = 25
low_mem = false
notrack = false
reports_only = false
report_output_level = "root"
skip_odf_reports = false
write_graph = false

[workflow]
b0_threshold = 50
infant = false
input_type = "qsiprep"
recon_spec = "mrtrix_multishell_msmt_ACT"  # "dsi_studio_gqi" "mrtrix_multishell_msmt_ACT-hsvs"
output_resolution = 1.8
spaces = "MNI152NLin2009cAsym"

[nipype]
crashfile_format = "txt"
get_linked_libs = false
nprocs = 24
omp_nthreads = 24
plugin = "MultiProc"
remove_unnecessary_outputs = true
resource_monitor = false
stop_on_first_crash = false
